apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  sources:
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.31.0
      helm:
        releaseName: argo-workflows
        valueFiles:
          - $values/packages/argo-workflows/dev/values.yaml
        parameters:
          - name: server.sso.issuer
            value: ${KEYCLOAK_MODERNENGG_URL}
          - name: server.sso.redirectUrl
            value: ${ARGO_REDIRECT_URL}
    - repoURL: ${GITHUB_URL}
      targetRevision: feature/upgradeToPathBasedRouting
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
