apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      path: ${PATH}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
